In [4]:
from tenten_v1 import makematrix
import numpy as np

## Problem 1 
### Part 1

In [31]:
def forward_1_1(X):
    """
    Forward model for problem 2.2-5
    X: array of unknowns [m1, m2, m3, m4]
    Returns: array of equations evaluated at X

    material balances:
        Total:          m1 = m2 + m3 + m4
        A:           0.3m1 = 0.3m3 + m4
        m1:             m1 = 100
        m2:             m2 = 50

    """
    m1, m2, m3, m4 = X

    m = 4 # 4 independent balance equations total, salt, draw chemical
    eq = np.zeros(m)

    # material balances, open system CV, steady-state, no reactions
    eq[0] = (m1)    - (m2 + m3  + m4)                # Total
    eq[1] = (0.3*m1)    - (0.3* m3 + m4)     # A
    eq[2] = m1 - 100     # m1
    eq[3] = m2 - 50 # m2

    return eq

In [59]:
"""
make matrices and solve the problem
"""
A,b = makematrix(forward_1_1,4) 
print(f"Matrix A:\n{A}")
print(f"Vector b:\n{b}")

solution = np.linalg.solve(A, b)

print(f'm3: {solution[2]:.2f}; m4: {solution[3]:.2f}')
print('No unit in this problem')

# of equations m = 4 and # of unknowns N = 4
Matrix A:
[[ 1.  -1.  -1.  -1. ]
 [ 0.3  0.  -0.3 -1. ]
 [ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]]
Vector b:
[ -0.  -0. 100.  50.]
m3: 28.57; m4: 21.43
No unit in this problem


### Part 2

In [33]:
def water_vapor_fraction(T):
    '''
    Input: T in deg C
    Output: mass fraction of water vapor in cool gas stream
    '''
    return 583 * (0.001 * np.exp(5132 / (T + 273.15)) - 356) ** (-1)


def forward_1_2(X):
    """
    Forward model for problem 2.2-5
    X: array of unknowns [m1, m2, m3a, m3h, m4]
    Returns: array of equations evaluated at X

    material balances:
        Total:          m1 + m2 = m3a + m3h + m4
        Air:            m1 = m3a
        m1:             m1 = 1
        m3h:            m3h = m3a * f(T)/(1 - f(T))
        energy:         whatever copied from answer key


    """
    m1, m2, m3a, m3h, m4 = X
    T = 11

    m = 5 
    eq = np.zeros(m)

    # material balances, open system CV, steady-state, no reactions
    eq[0] = (m1 + m2)    - (m3a + m3h  + m4)                # Total
    eq[1] = m1 - m3a     # Air
    eq[2] = m1 - 1     # m1
    eq[3] = m3h - m3a * water_vapor_fraction(T) / (1 - water_vapor_fraction(T)) # water vapor fraction
    eq[4] = m1 * 1.0 * (35 - T) - m3h * (4.2 * (100 - 10) + 2300 + 2.0 *(T - 100)) -  m4 * (4.2 * (T - 10))
 
    return eq

In [58]:
"""
make matrices and solve the problem
"""
A,b = makematrix(forward_1_2,5) 
print(f"Matrix A:\n{A}")
print(f"Vector b:\n{b}")

solution = np.linalg.solve(A, b)

print(f'm2: {solution[1]:.4f} kg/s')
print(f'm3, air: {solution[2]:.4f} kg/s')
print(f'm3, h2o: {solution[3]:.4f} kg/s')
print(f'm4: {solution[4]:.4f} kg/s')

# of equations m = 5 and # of unknowns N = 5
Matrix A:
[[ 1.00e+00  1.00e+00 -1.00e+00 -1.00e+00 -1.00e+00]
 [ 1.00e+00  0.00e+00 -1.00e+00  0.00e+00  0.00e+00]
 [ 1.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00 -8.47e-03  1.00e+00  0.00e+00]
 [ 2.40e+01  0.00e+00  0.00e+00 -2.50e+03 -4.20e+00]]
Vector b:
[-0. -0.  1. -0. -0.]
m2: 0.6819 kg/s
m3, air: 1.0000 kg/s
m3, h2o: 0.0085 kg/s
m4: 0.6735 kg/s


### Part 3

In [35]:
def forward_1_3(X):
    """
    Forward model for problem 2.2-5
    X: array of unknowns [m1, m2, m3a, m3h, m4]
    Returns: array of equations evaluated at X

    material balances:
        Total:          m1 + m2 = m3a + m3h + m4
        Air:            m1 = m3a
        water:          m2 = 1
        m3h:            m3h = m3a * f(T)/(1 - f(T))
        energy:         whatever copied from answer key


    """
    m1, m2, m3a, m3h, m4 = X
    T = 11

    m = 5 
    eq = np.zeros(m)

    # material balances, open system CV, steady-state, no reactions
    eq[0] = (m1 + m2)    - (m3a + m3h  + m4)                # Total
    eq[1] = m1 - m3a     # Air
    eq[2] = m2 - 1     # m1
    eq[3] = m3h - m3a * water_vapor_fraction(T) / (1 - water_vapor_fraction(T)) # water vapor fraction
    eq[4] = m1 * 1.0 * (35 - T) - m3h * (4.2 * (100 - 10) + 2300 + 2.0 *(T - 100)) -  m4 * (4.2 * (T - 10))
    
    return eq

In [36]:
"""
make matrices and solve the problem
"""
A,b = makematrix(forward_1_3,5) 
print(f"Matrix A:\n{A}")
print(f"Vector b:\n{b}")

solution = np.linalg.solve(A, b)

print(f'm1: {solution[0]:.4f} kg/s')
print(f'm3a: {solution[2]:.4f} kg/s')
print(f'm3h: {solution[3]:.4f} kg/s')
print(f'm4: {solution[4]:.4f} kg/s')

# of equations m = 5 and # of unknowns N = 5
Matrix A:
[[ 1.00e+00  1.00e+00 -1.00e+00 -1.00e+00 -1.00e+00]
 [ 1.00e+00  0.00e+00 -1.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  1.00e+00  0.00e+00  0.00e+00  0.00e+00]
 [ 0.00e+00  0.00e+00 -8.47e-03  1.00e+00  0.00e+00]
 [ 2.40e+01  0.00e+00  0.00e+00 -2.50e+03 -4.20e+00]]
Vector b:
[-0. -0.  1. -0. -0.]
m1: 1.4664 kg/s
m3a: 1.4664 kg/s
m3h: 0.0124 kg/s
m4: 0.9876 kg/s


### Part 4

Energy balance on condenser cannot be computed, as information on $Cp_{\text{water}(v)}$, $Q$, $W$, are not given. 

In [61]:
def forward_1_4(X):
    """
    Forward model for problem 2.2-5
    X:
    m1a: m1_air
    m1h: m1_h2o(v)
    n3a: n3_air
    n3h: n3_h2o
    P: operating pressure
    Returns: array of equations evaluated at X
    """
    m1a, m1h, n3a, n3h, m2, P = X

    MW_air = 0.029  # kg/mol
    MW_h2o = 0.018 # kg/mol
    P_vap = 92.5 # mmHg
    w_cond = ... # unknown
    cp_choc = 3.5 # J/molC
    cp_h2o = 5 # J/molC, liquid water at 50C 

    m = 6
    eq = np.zeros(m)

    # equations
    # material balances
    eq[0] = MW_air* n3a + MW_air * n3h - (m1a + m1h - m2)   # material balance on condenser
    eq[1] = m1h - n3h * MW_h2o - m2 # material balance on water, condenser

    # energy balances
    eq[2] = m2 - 3.5 / 5 * 125      # energy balance on heat exchanger
    eq[3] = 2256 * m1h +  ... # + W + Q + sum nH         # energy balance on condenser

    # Rault's law
    eq[4] = P_vap - P * (n3h / (n3h + n3a)) # Rault's law, non linear!
    
    # inlet constraint
    eq[5] = m1a + m1h - 150         # Total inlet 

   
    return eq

def operating_pressure(m1a, m1h, m2):
    '''
    Input: m1, m2 in kg/s
    output  : operating pressure in Pa
    '''
    P_vap = 92.5 # mmHg
    MW_air = 0.029  
    MW_h2o = 0.018 # kg/mol
    return P_vap * MW_h2o * (m1a + m1h - m2) / (MW_air * (m1h - m2))

In [62]:
"""
make matrices and solve the problem
"""
A,b = makematrix(forward_1_4,6) 
print(f"Matrix A:\n{A}")
print(f"Vector b:\n{b}")

solution = np.linalg.solve(A, b)

m1 = solution[0] + solution[1]
x1air = solution[0] / m1
x1h2o = solution[1] / m1
n3 = solution[2] + solution[3]  
y3air = solution[2] / n3
y3h2o = solution[3] / n3
m2 = solution[4]

print(f'x1_air: {x1air:.4f}')
print(f'x1_h2o: {x1h2o:.4f}')
print(f'n3: {n3:.4f} mol/s')
print(f'y3_air: {y3air:.4f}')
print(f'y3_h2o: {y3h2o:.4f}')
print(f'm2: {m2:.2f} kg/s')

print(f'Operating pressure: {operating_pressure(solution[0], solution[1], m2):.2f} mmHg')

TypeError: unsupported operand type(s) for +: 'float' and 'ellipsis'

## Problem 2

### Part 1
By Le Chatelier's, a drop in pressure would push $l \to g$ equilibrium forward to counter such change; thus some liquid would be vaporized.

### Part 2

In [67]:
def forward_2(X):
    """
    Forward model for problem 2.2-5
    X: array of unknowns nb, nt, ne, nx: flow rates of outlet vapor for each component (mol/min)
    n_liq: flow rate of outlet liquid, total (mol/min)
    Returns: array of equations evaluated at X
    """
    nb, nt, ne, nx, n_liq= X

    m = 5
    eq = np.zeros(m)

    # material balances, open system CV, steady-state, no reactions
    eq[0] = 100 - 0.08 * n_liq - nb        # material balance for B
    eq[1] = 100 - 0.17 * n_liq - nt        # material balance for T
    eq[2] = 100 - 0.35 * n_liq - ne        # material balance for E
    eq[3] = 100 - 0.4 * n_liq - nx         # material balance for X
    # energy balance
    eq[4] = 30.765 * nb + 33.47 * nt + 35.98 * ne + 36.07 * nx - 125 * (0.135 * 100 + 0.160 * 100 + 0.185 * 100 + 0.181 * 100)
    
    return eq

In [69]:
"""
make matrices and solve the problem
"""
A,b = makematrix(forward_2,5) 
print(f"Matrix A:\n{A}")
print(f"Vector b:\n{b}")

solution = np.linalg.solve(A, b)

n_gas = 400 - solution[4]
yb = solution[0] / n_gas
yt = solution[1] / n_gas
ye = solution[2] / n_gas
yx = solution[3] / n_gas

print('\n')
print(f'Outlet vapor flow rate: {n_gas:.2f} mol/min')
print(f'Composition: B: {yb:.3f}; T: {yt:.3f}, E:{ye:.3f}, X: {yx:.3f}')

# of equations m = 5 and # of unknowns N = 5
Matrix A:
[[-1.    0.    0.    0.   -0.08]
 [ 0.   -1.    0.    0.   -0.17]
 [ 0.    0.   -1.    0.   -0.35]
 [ 0.    0.    0.   -1.   -0.4 ]
 [30.76 33.47 35.98 36.07  0.  ]]
Vector b:
[-100.  -100.  -100.  -100.  8262.5]


Outlet vapor flow rate: 247.44 mol/min
Composition: B: 0.355; T: 0.299, E:0.188, X: 0.158


### Part 4
Work done by the system to cause the 'sudden pressure reduction' is missing from the energy balance, which should decrease the flow rate of vapors computed. 